import { initializeApp } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js";
import { getFirestore, collection, addDoc, updateDoc, deleteDoc, doc, onSnapshot, query, where, getDocs } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyAGWi3iNv1bROpOoulUwh20XSsLokFYrz8x",authDomain:"fir-13-app.firebaseapp.com",projectId:"fir-13-app",storageBucket:"fir-13-app.firebasestorage.app",messagingSenderId:"1080215970738",appId:"1:1080215970738:web:2d66b3b8a9ea26f1e6baab",measurementId:"G-70HBSY6MC6"};
const db=getFirestore(initializeApp(firebaseConfig));

const I={
 ru:{app:"АССИСТЕНТ ПО УЧАСТКАМ",home:"Главная",territories:"Участки",publishers:"Возвещатели",connected:"Firebase подключен",addCity:"Город",editCity:"Изменить город",renameCity:"Изменить название",cityMap:"Изменить ссылку на карту",free:"Свободно",busy:"В обработке",overdue:"Просрочено",waiting:"Ожидание",map:"Карта",territory:"Участок",issue:"Выдать",ret:"Сдать",history:"История выдач",empty:"История пуста",issued:"Выдан",returned:"Сдан",inProgress:"В ОБРАБОТКЕ",due:"Срок сдачи (4 мес.):",lastReturn:"Последняя сдача:",again:"Можно выдать снова:",daysAgain:"До повторной выдачи:",days:"дн.",noMap:"Ссылка не добавлена",nobody:"Никому не выдан",russian:"Русскоговорящие:",addPublisher:"Добавить возвещателя",search:"Поиск по имени",choosePublisher:"Выберите возвещателя",inBase:"в базе",cancel:"Отмена",ok:"ОК",confirm:"Подтвердить",cantIssue:"Этот участок пока нельзя выдать. С момента последней сдачи должен пройти один год.",publisherExists:"Такой возвещатель уже есть в базе.",firstPublisher:"Сначала добавьте возвещателя в базу."},
 fr:{app:"ASSISTANT DE TERRITOIRES",home:"Accueil",territories:"Territoires",publishers:"Proclamateurs",connected:"Firebase connecté",addCity:"Ville",editCity:"Modifier la ville",renameCity:"Modifier le nom",cityMap:"Modifier le lien de la carte",free:"Libres",busy:"Attribués",overdue:"En retard",waiting:"Attente",map:"Carte",territory:"Territoire",issue:"Attribuer",ret:"Rendre",history:"Historique",empty:"L'historique est vide",issued:"Attribué",returned:"Rendu",inProgress:"EN COURS",due:"Échéance (4 mois) :",lastReturn:"Dernier retour :",again:"Peut être attribué à nouveau :",daysAgain:"Avant la prochaine attribution :",days:"j.",noMap:"Aucun lien",nobody:"Non attribué",russian:"Russophones :",addPublisher:"Ajouter un proclamateur",search:"Recherche par nom",choosePublisher:"Choisir un proclamateur",inBase:"dans la base",cancel:"Annuler",ok:"OK",confirm:"Confirmer",cantIssue:"Ce territoire ne peut pas encore être attribué. Un an doit s'écouler depuis son dernier retour.",publisherExists:"Ce proclamateur existe déjà.",firstPublisher:"Ajoutez d’abord un proclamateur dans la base."}
};
let lang='ru',view='home',cities=[],territories=[],publishers=[],activeCityId=null,unsubTerritories=null,territorySig='',publisherSig='',historyTerritoryId=null;
const $=id=>document.getElementById(id), tr=k=>I[lang][k]||k;

function dateStr(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function parseDate(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s||''))return null;const [y,m,d]=s.split('-').map(Number),x=new Date(y,m-1,d);x.setHours(0,0,0,0);return x.getFullYear()===y&&x.getMonth()===m-1&&x.getDate()===d?x:null}
function fmt(s){if(!s)return'';const p=s.split('-');return p.length===3?`${p[2]}${lang==='fr'?'/':'.'}${p[1]}${lang==='fr'?'/':'.'}${p[0]}`:s}
function inputDate(s){if(!s?.trim())return null;const z=s.trim(),sep=z.includes('/')?'/':z.includes('.')?'.':null;if(!sep)return z;const p=z.split(sep);return p.length===3?`${p[2]}-${p[1].padStart(2,'0')}-${p[0].padStart(2,'0')}`:z}
function addYear(s){const d=parseDate(s);if(!d)return null;const x=new Date(d);x.setFullYear(x.getFullYear()+1);return x}
function localDate(d){return d?dateStr(d):''}
function latestCompleted(t){const a=(t.history||[]).filter(h=>parseDate(h?.returnedAt));return a.reduce((best,h)=>!best||parseDate(h.returnedAt)>parseDate(best.returnedAt)?h:best,null)}
function lastHistory(t){return (t.history||[]).at(-1)||null}
function canIssue(t){const h=latestCompleted(t),d=h&&addYear(h.returnedAt);if(!d)return true;const today=parseDate(dateStr());return today>=d}
function waitDays(t){const h=latestCompleted(t),d=h&&addYear(h.returnedAt);if(!d)return 0;return Math.max(0,Math.ceil((d-parseDate(dateStr()))/86400000))}
function norm(s){return(s||'').trim().replace(/\s+/g,' ').toLocaleLowerCase()}

function applyText(){document.documentElement.lang=lang;$('app-title').textContent=tr('app');$('nav-home-label').textContent=tr('home');$('nav-territories-label').textContent=tr('territories');$('nav-publishers-label').textContent=tr('publishers');$('btn-add-city-label').textContent=tr('addCity');$('btn-edit-city-label').textContent=tr('editCity');$('stat-free-label').textContent=tr('free');$('stat-busy-label').textContent=tr('busy');$('stat-overdue-label').textContent=tr('overdue');$('stat-waiting-label').textContent=tr('waiting');$('map-label').textContent=tr('map');$('add-territory-label').textContent=tr('territory');$('publishers-title').textContent=tr('publishers');$('publisher-add-label').textContent=tr('addPublisher');$('publishers-search').placeholder=tr('search');$('publisher-picker-title').textContent=tr('choosePublisher');$('publisher-picker-search').placeholder=tr('search');$('pub-base-label').textContent=tr('inBase');if(view==='territories')renderTerritories();if(view==='publishers')renderPublishers()}
window.toggleLanguage=()=>{lang=lang==='ru'?'fr':'ru';$('lang-slider').classList.toggle('translate-x-[calc(100%+4px)]',lang==='fr');$('lang-slider').classList.toggle('bg-rose-500',lang==='fr');$('lang-slider').classList.toggle('bg-emerald-500',lang==='ru');applyText()};

function setView(v){view=v;['home','territories','publishers'].forEach(x=>{$(`${x}-page`).classList.toggle('hidden',x!==v);$(`nav-${x}`).classList.toggle('nav-active',x===v)});if(v!=='territories'&&unsubTerritories){unsubTerritories();unsubTerritories=null}if(innerWidth<1024)$('sidebar').classList.remove('mobile-open')}
window.showHomePage=()=>setView('home');window.showPublishersPage=()=>{setView('publishers');renderPublishers()};window.toggleMobileSidebar=()=>$('sidebar').classList.toggle('mobile-open');window.toggleTerritoriesMenu=()=>{$('cities-container').classList.toggle('hidden');$('territory-chevron').classList.toggle('rotate-180')};
window.showTerritoryCity=id=>{activeCityId=id;setView('territories');$('cities-container').classList.remove('hidden');$('territory-chevron').classList.add('rotate-180');$('city-controls').classList.remove('hidden');$('city-controls').classList.add('flex');$('active-city-title').textContent=cities.find(c=>c.id===id)?.name||'';renderCities();updateMap();territorySig='';subscribeTerritories()};

let dialogResolve=null;
function dialog(title,fields){return new Promise(r=>{dialogResolve=r;$('dialog-title').textContent=title;$('dialog-fields').innerHTML='';fields.forEach((f,i)=>{const w=document.createElement('label');w.className='block space-y-1';const s=document.createElement('span');s.className='text-[10px] uppercase text-slate-400 font-bold';s.textContent=f.label;const inp=document.createElement('input');inp.id=`dlg-${i}`;inp.value=f.value||'';inp.placeholder=f.placeholder||'';inp.className='w-full h-10 bg-slate-950 border border-slate-800 rounded-xl px-3 text-xs focus:outline-none focus:border-indigo-500';w.append(s,inp);$('dialog-fields').append(w)});$('dialog-modal').classList.remove('hidden');$('dialog-modal').classList.add('flex');$('dlg-0')?.focus()})}
window.closeDialog=ok=>{const r=dialogResolve;dialogResolve=null;$('dialog-modal').classList.add('hidden');$('dialog-modal').classList.remove('flex');r?.(ok?[...$('dialog-fields').querySelectorAll('input')].map(x=>x.value):null)};
let confirmResolve=null;function confirmBox(text){return new Promise(r=>{confirmResolve=r;$('confirm-text').textContent=text;$('confirm-modal').classList.remove('hidden');$('confirm-modal').classList.add('flex')})}window.closeConfirm=ok=>{const r=confirmResolve;confirmResolve=null;$('confirm-modal').classList.add('hidden');$('confirm-modal').classList.remove('flex');r?.(ok)};

function renderCities(){$('cities-container').innerHTML='';[...cities].sort((a,b)=>(a.name||'').localeCompare(b.name||'')).forEach(c=>{const b=document.createElement('button');b.textContent=c.name;b.onclick=()=>showTerritoryCity(c.id);b.className=`w-full text-left px-3 py-2 rounded-xl text-xs ${view==='territories'&&activeCityId===c.id?'font-bold bg-indigo-600 text-white':'font-semibold text-slate-400 hover:bg-slate-800 hover:text-white'}`;$('cities-container').append(b)})}
function updateMap(){const c=cities.find(x=>x.id===activeCityId),a=$('map-link');if(c?.mapUrl&&c.mapUrl!=='#'){a.href=c.mapUrl;a.classList.remove('hidden');a.classList.add('flex')}else{a.classList.add('hidden');a.classList.remove('flex')}}

window.addCity=async()=>{const v=await dialog(tr('addCity'),[{label:lang==='fr'?'Nom de la ville':'Название города'},{label:tr('map'),placeholder:'https://www.google.com/maps/d/...'}]);if(!v?.[0]?.trim())return;await addDoc(collection(db,'cities'),{name:v[0].trim(),mapUrl:v[1]?.trim()||''})};
window.editCityMenu=()=>{$('city-menu').classList.toggle('hidden')};document.addEventListener('click',e=>{if(!e.target.closest('#city-menu-wrap'))$('city-menu')?.classList.add('hidden')});
window.renameCity=async()=>{const c=cities.find(x=>x.id===activeCityId);if(!c)return;const v=await dialog(tr('renameCity'),[{label:tr('renameCity'),value:c.name}]);if(v?.[0]?.trim())await updateDoc(doc(db,'cities',c.id),{name:v[0].trim()})};
window.editCityMap=async()=>{const c=cities.find(x=>x.id===activeCityId);if(!c)return;const v=await dialog(tr('cityMap'),[{label:tr('map'),value:c.mapUrl||''}]);if(v)await updateDoc(doc(db,'cities',c.id),{mapUrl:v[0].trim()})};
window.addTerritory=async()=>{if(!activeCityId)return;const v=await dialog(tr('territory'),[{label:lang==='fr'?'Numéro':'Номер участка'},{label:tr('map'),placeholder:'https://...'}]);if(!v?.[0]?.trim())return;await addDoc(collection(db,'territories'),{cityId:activeCityId,number:v[0].trim(),mapUrl:v[1]?.trim()||'',russianSpeakers:0,history:[]})};

function subscribeTerritories(){if(unsubTerritories)unsubTerritories();const q=query(collection(db,'territories'),where('cityId','==',activeCityId));unsubTerritories=onSnapshot(q,s=>{const next=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>parseInt(a.number)-parseInt(b.number)||(a.number||'').localeCompare(b.number||''));const sig=JSON.stringify(next);if(sig===territorySig)return;territorySig=sig;territories=next;if(view==='territories')renderTerritories();if(historyTerritoryId)showHistory(historyTerritoryId)})}

function renderTerritories(){let free=0,busy=0,over=0,waiting=0;$('grid').innerHTML='';territories.forEach((t,i)=>{const last=lastHistory(t),isBusy=!!last&&!last.returnedAt,lastDone=latestCompleted(t),isWaiting=!isBusy&&!!lastDone&&!canIssue(t);let days=0,isOver=false,due='-';if(isBusy&&parseDate(last.issuedAt)){const start=parseDate(last.issuedAt),today=parseDate(dateStr()),d=new Date(start);d.setMonth(d.getMonth()+4);days=Math.floor((today-start)/86400000);isOver=today>d;due=fmt(localDate(d))}if(isBusy)(isOver?over++:busy++);else if(isWaiting)waiting++;else free++;
 let cls='bg-emerald-900/40 border-emerald-500/60',badge=`<span class="badge bg-emerald-950 text-emerald-300 border-emerald-500/30">${tr('free')}</span>`;if(isBusy&&!isOver){cls='bg-blue-900/40 border-blue-500/60';badge=`<span class="badge bg-blue-950 text-blue-300 border-blue-500/30">${tr('busy')} (${days} ${tr('days')})</span>`}if(isOver){cls='bg-rose-900/40 border-rose-500/70';badge=`<span class="badge bg-rose-950 text-rose-300 border-rose-500/30">${tr('overdue')} (${days} ${tr('days')})</span>`}if(isWaiting){cls='bg-amber-900/40 border-amber-500/70';badge=`<span class="badge bg-amber-950 text-amber-300 border-amber-500/30">${tr('waiting')}</span>`}
 let info=isBusy?`<p><i class="fa-solid fa-user mr-1"></i><b>${esc(last.publisher)}</b></p><p class="text-[11px] text-slate-300">${tr('due')} <b>${due}</b></p>`:isWaiting?`<p class="font-bold text-amber-200"><i class="fa-solid fa-hourglass-half mr-1"></i>${tr('waiting')}</p><p class="text-[11px] text-amber-100/80">${tr('lastReturn')} <b>${fmt(lastDone.returnedAt)}</b></p><p class="text-[11px] text-amber-100/80">${tr('again')} <b>${fmt(localDate(addYear(lastDone.returnedAt)))}</b></p><p class="text-[11px] text-amber-300">${tr('daysAgain')} <b class="text-white">${waitDays(t)}</b> ${tr('days')}</p>`:`<p class="italic text-slate-300/70">${tr('nobody')}</p>`;
 let action=isBusy?`<button onclick="returnTerritory('${t.id}')" class="action-btn">${tr('ret')}</button>`:isWaiting?`<button disabled class="action-btn opacity-45 cursor-not-allowed"><i class="fa-solid fa-lock mr-1"></i>${tr('issue')}</button>`:`<button onclick="issueTerritory('${t.id}')" class="h-8 px-3.5 bg-white text-slate-950 rounded-xl text-xs font-bold">${tr('issue')}</button>`;
 const card=document.createElement('article');card.className=`border ${cls} rounded-3xl p-4 space-y-4 shadow-xl`;card.innerHTML=`<div class="flex justify-between gap-2"><div><span class="text-[10px] text-slate-400 uppercase font-bold">${tr('territory')}</span><h3 class="text-xl font-extrabold">№ ${esc(t.number)}</h3></div>${badge}</div><div class="space-y-2 text-xs">${info}<p title="${tr('russian')}"><i class="fa-solid fa-user-group text-sky-400 mr-1"></i><b>${t.russianSpeakers||0}</b></p><div>${t.mapUrl?`<a href="${attr(t.mapUrl)}" target="_blank" class="mini-btn"><i class="fa-solid fa-map mr-1"></i>${tr('map')}</a>`:`<span class="text-[10px] text-slate-400 italic">${tr('noMap')}</span>`}</div></div><div class="pt-3 border-t border-white/10 flex justify-between"><div class="flex gap-1"><button onclick="editTerritory('${t.id}')" class="square-btn"><i class="fa-solid fa-pen"></i></button><button onclick="showHistory('${t.id}')" class="square-btn"><i class="fa-solid fa-clock-rotate-left"></i></button></div>${action}</div>`;$('grid').append(card)});$('st-free').textContent=free;$('st-busy').textContent=busy;$('st-overdue').textContent=over;$('st-waiting').textContent=waiting}
function esc(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML}function attr(v){return esc(v).replace(/"/g,'&quot;')}

window.editTerritory=async id=>{const t=territories.find(x=>x.id===id);if(!t)return;const v=await dialog(`${tr('territory')} №${t.number}`,[{label:lang==='fr'?'Numéro':'Номер',value:t.number},{label:tr('map'),value:t.mapUrl||''},{label:tr('russian'),value:String(t.russianSpeakers||0)}]);if(!v)return;await updateDoc(doc(db,'territories',id),{number:v[0].trim()||t.number,mapUrl:v[1].trim(),russianSpeakers:Math.max(0,parseInt(v[2])||0)})};
window.issueTerritory=async id=>{const t=territories.find(x=>x.id===id);if(!t)return;if(!canIssue(t)){const h=latestCompleted(t);alert(`${tr('cantIssue')}\n\n${tr('lastReturn')} ${fmt(h.returnedAt)}\n${tr('again')} ${fmt(localDate(addYear(h.returnedAt)))}`);return}if(!publishers.length){alert(tr('firstPublisher'));showPublishersPage();return}const p=await pickPublisher();if(!p)return;const history=[...(t.history||[]),{publisherId:p.id,publisher:p.fullName,issuedAt:dateStr(),returnedAt:null}];await updateDoc(doc(db,'territories',id),{history})};
window.returnTerritory=async id=>{const t=territories.find(x=>x.id===id),history=[...(t?.history||[])];if(!history.length)return;history[history.length-1]={...history.at(-1),returnedAt:dateStr()};await updateDoc(doc(db,'territories',id),{history})};

window.showHistory=id=>{historyTerritoryId=id;const t=territories.find(x=>x.id===id);if(!t)return;$('history-title').textContent=`${tr('history')} №${t.number}`;$('history-list').innerHTML='';if(!(t.history||[]).length)$('history-list').innerHTML=`<p class="text-xs text-slate-400 italic">${tr('empty')}</p>`;(t.history||[]).forEach((h,i)=>{const r=document.createElement('div');r.className='bg-slate-950 border border-slate-800 rounded-2xl p-3 flex justify-between gap-2';r.innerHTML=`<div><b>#${i+1} ${esc(h.publisher)}</b><p class="text-[11px] text-slate-400">${tr('issued')}: ${fmt(h.issuedAt)} | ${tr('returned')}: ${h.returnedAt?fmt(h.returnedAt):tr('inProgress')}</p></div><div class="flex gap-1"><button onclick="editHistory(${i})" class="square-btn"><i class="fa-solid fa-pen"></i></button><button onclick="deleteHistory(${i})" class="square-btn text-rose-400"><i class="fa-solid fa-trash"></i></button></div>`;$('history-list').append(r)});$('history-modal').classList.remove('hidden');$('history-modal').classList.add('flex')};
window.closeHistory=()=>{historyTerritoryId=null;$('history-modal').classList.add('hidden');$('history-modal').classList.remove('flex')};
window.editHistory=async i=>{const t=territories.find(x=>x.id===historyTerritoryId),h=t?.history?.[i];if(!h)return;const v=await dialog(`${tr('history')} #${i+1}`,[{label:tr('publishers'),value:h.publisher},{label:tr('issued'),value:fmt(h.issuedAt)},{label:tr('returned'),value:fmt(h.returnedAt)}]);if(!v)return;const a=[...t.history];a[i]={...h,publisher:v[0].trim()||h.publisher,issuedAt:inputDate(v[1])||h.issuedAt,returnedAt:inputDate(v[2])};await updateDoc(doc(db,'territories',t.id),{history:a})};
window.deleteHistory=async i=>{const t=territories.find(x=>x.id===historyTerritoryId);if(!t?.history?.[i])return;if(!await confirmBox(`${lang==='fr'?'Supprimer':'Удалить'} #${i+1} (${t.history[i].publisher})?`))return;const a=[...t.history];a.splice(i,1);await updateDoc(doc(db,'territories',t.id),{history:a})};

async function seedPublishers(){try{const [ps,ts]=await Promise.all([getDocs(collection(db,'publishers')),getDocs(collection(db,'territories'))]),keys=new Set(ps.docs.map(d=>norm(d.data().fullName))),names=new Map();ts.docs.forEach(d=>(d.data().history||[]).forEach(h=>{const n=(h?.publisher||'').trim().replace(/\s+/g,' '),k=norm(n);if(k&&!keys.has(k))names.set(k,n)}));for(const[k,fullName]of names){await addDoc(collection(db,'publishers'),{fullName,nameKey:k,createdAt:dateStr()});keys.add(k)}}catch(e){console.error('Publisher seed:',e)}}
function subscribePublishers(){onSnapshot(collection(db,'publishers'),s=>{const next=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.fullName||'').localeCompare(b.fullName||''));const sig=JSON.stringify(next);if(sig===publisherSig)return;publisherSig=sig;publishers=next;if(view==='publishers')renderPublishers();if(!$('publisher-picker-modal').classList.contains('hidden'))renderPicker()})}
function renderPublishers(){const q=($('publishers-search').value||'').toLocaleLowerCase(),list=$('publishers-list');$('publishers-count').textContent=publishers.length;list.innerHTML='';publishers.filter(p=>(p.fullName||'').toLocaleLowerCase().includes(q)).forEach(p=>{const r=document.createElement('div');r.className='bg-slate-900/80 border border-slate-800 rounded-2xl p-3.5 flex justify-between items-center';r.innerHTML=`<b>${esc(p.fullName)}</b><div class="flex gap-1"><button onclick="editPublisher('${p.id}')" class="square-btn"><i class="fa-solid fa-pen"></i></button><button onclick="deletePublisher('${p.id}')" class="square-btn text-rose-400"><i class="fa-solid fa-trash"></i></button></div>`;list.append(r)})}window.renderPublishers=renderPublishers;
window.addPublisher=async()=>{const v=await dialog(tr('addPublisher'),[{label:tr('publishers'),placeholder:'Иван Иванов'}]),fullName=v?.[0]?.trim().replace(/\s+/g,' ');if(!fullName)return;if(publishers.some(p=>norm(p.fullName)===norm(fullName))){alert(tr('publisherExists'));return}await addDoc(collection(db,'publishers'),{fullName,nameKey:norm(fullName),createdAt:dateStr()})};
window.editPublisher=async id=>{const p=publishers.find(x=>x.id===id);if(!p)return;const v=await dialog(lang==='fr'?'Modifier le proclamateur':'Изменить возвещателя',[{label:tr('publishers'),value:p.fullName}]),fullName=v?.[0]?.trim().replace(/\s+/g,' ');if(!fullName)return;if(publishers.some(x=>x.id!==id&&norm(x.fullName)===norm(fullName))){alert(tr('publisherExists'));return}await updateDoc(doc(db,'publishers',id),{fullName,nameKey:norm(fullName)})};
window.deletePublisher=async id=>{const p=publishers.find(x=>x.id===id);if(!p)return;if(await confirmBox(`${lang==='fr'?'Supprimer':'Удалить'} ${p.fullName}?`))await deleteDoc(doc(db,'publishers',id))};
let pickerResolve=null;function pickPublisher(){return new Promise(r=>{pickerResolve=r;$('publisher-picker-search').value='';renderPicker();$('publisher-picker-modal').classList.remove('hidden');$('publisher-picker-modal').classList.add('flex');$('publisher-picker-search').focus()})}function renderPicker(){const q=$('publisher-picker-search').value.toLocaleLowerCase(),list=$('publisher-picker-list');list.innerHTML='';publishers.filter(p=>(p.fullName||'').toLocaleLowerCase().includes(q)).forEach(p=>{const b=document.createElement('button');b.className='w-full text-left p-3 rounded-xl bg-slate-950 hover:bg-indigo-950 border border-slate-800';b.textContent=p.fullName;b.onclick=()=>closePicker(p);list.append(b)})}window.renderPicker=renderPicker;function closePicker(p){const r=pickerResolve;pickerResolve=null;$('publisher-picker-modal').classList.add('hidden');$('publisher-picker-modal').classList.remove('flex');r?.(p||null)}window.closePicker=()=>closePicker(null);

window.exportOfficialRegister=()=>{const city=cities.find(c=>c.id===activeCityId);if(!city)return;const max=Math.max(1,...territories.map(t=>(t.history||[]).length));let rows='';territories.forEach(t=>{let names='',dates='';for(let i=0;i<max;i++){const h=t.history?.[i];names+=`<td colspan="2"><b>${h?esc(h.publisher):''}</b></td>`;dates+=h?`<td>${fmt(h.issuedAt)}</td><td>${h.returnedAt?fmt(h.returnedAt):'En cours'}</td>`:'<td></td><td></td>'}rows+=`<tr><td rowspan="2"><b>${esc(t.number)}</b></td><td rowspan="2">${fmt(latestCompleted(t)?.returnedAt)}</td>${names}</tr><tr>${dates}</tr>`});const heads='<th colspan="2">Attribué à</th>'.repeat(max),subs='<th>Attribué le</th><th>Entièrement parcouru le</th>'.repeat(max),html=`<html><head><meta charset="UTF-8"><style>body{font-family:Arial;font-size:9pt}table{border-collapse:collapse}th,td{border:1px solid #000;padding:3px;text-align:center;white-space:nowrap}th{background:#eee}</style></head><body><h2>REGISTRE D’ATTRIBUTION DES TERRITOIRES</h2><p><b>Année de service :</b> ${new Date().getFullYear()} &nbsp; <b>Ville :</b> ${esc(city.name)}</p><table><thead><tr><th rowspan="2">Terr. n°</th><th rowspan="2">Parcouru pour la dernière fois le*</th>${heads}</tr><tr>${subs}</tr></thead><tbody>${rows}</tbody></table><p><i>* Lorsque vous commencez une nouvelle feuille, notez dans cette colonne la date à laquelle chaque territoire a été entièrement parcouru pour la dernière fois.</i></p><p>S-13-F 1/22</p></body></html>`;const url=URL.createObjectURL(new Blob(['\ufeff'+html],{type:'application/msword;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`S-13_${city.name.replace(/[^a-z0-9]/gi,'_').toLowerCase()}.doc`;a.click();URL.revokeObjectURL(url)};

function scheduleMidnight(){const n=new Date(),d=new Date(n);d.setDate(d.getDate()+1);d.setHours(0,0,1,0);setTimeout(()=>{if(view==='territories')renderTerritories();scheduleMidnight()},Math.max(1000,d-n))}

async function init(){try{const s=await getDocs(collection(db,'cities'));cities=s.docs.map(d=>({id:d.id,...d.data()}));activeCityId=cities[0]?.id||null;renderCities();onSnapshot(collection(db,'cities'),snap=>{const next=snap.docs.map(d=>({id:d.id,...d.data()}));if(JSON.stringify(next)===JSON.stringify(cities))return;cities=next;renderCities();if(view==='territories'){$('active-city-title').textContent=cities.find(c=>c.id===activeCityId)?.name||'';updateMap()}});await seedPublishers();subscribePublishers();$('db-status').innerHTML=`<span class="w-2 h-2 rounded-full bg-emerald-400"></span>${tr('connected')}`;applyText();showHomePage();scheduleMidnight()}catch(e){console.error(e);$('db-status').innerHTML='<span class="w-2 h-2 rounded-full bg-rose-500"></span>Firebase error'}}
init();
